openapi: 3.0.0
info:
  title: Titan API v1
  description: Malware indicators lookup API.
  version: 1.19.7
servers:
  - url: https://api.intel471.com/v1
    description: "Production server."
paths:
  /indicators:
    get:
      summary: Search Malware Intelligence Indicators
      description: "Returns list of Indicators matching filter criteria. Supported types are IPv4 address, URL and file hashes"
      parameters:
        - name: indicator
          in: query
          schema:
            type: string
          description: Free text indicator search (all fields included).
        - name: indicatorType
          in: query
          schema:
            type: string
          description: "Search indicators by type (e.g. `file`, `ipv4`, `url`)."
      responses:
        '200':
          description: A JSON array of malware indicators
          content:
            application/json:
              schema:
                type: object
                required:
                  - indicatorTotalCount
                properties:
                  indicatorTotalCount:
                    type: integer
                    description: Total count of matched indicators.
                  indicatorPartialResult:
                    type: boolean
                    description: Indicates whether response contains partial result. It could be in case when request took too long and was terminated by timeout.
                  indicators:
                    type: array
                    description: "List of `Indicators`"
                    items:
                      type: object
                      required:
                        - last_updated
                        - data
                      properties:
                        last_updated:
                          type: integer
                          format: int64
                          description: Indicator last modification date.
                        data:
                          type: object
                          description: Sub-document containing indicator information. Might contain fields specific for different indicator types which are not described in current documentation.
                          required:
                            - uid
                            - threat
                            - indicator_type
                            - indicator_data
                            - expiration
                            - confidence
                          properties:
                            uid:
                              type: string
                              description: Indicator's UID
                            threat:
                              type: object
                              description: Detailed information about a threat.
                              required:
                                - uid
                                - type
                                - data
                              properties:
                                uid:
                                  type: string
                                  description: Unique threat identifier.
                                type:
                                  type: string
                                  description: "Threat type: `malware`, `proxy_service` etc."
                                data:
                                  type: object
                                  description: "Additional details about a threat such as service `provider`, `malware family`, `malware family version`, etc."
                                  properties:
                                    family:
                                      type: string
                                      description: "Malware family: `gozi_isfb`, `smokeloader`, `trickbot` etc (for `malware` threat type)."
                                    malware_family_profile_uid:
                                      type: string
                                      description: Malware family profile UID.
                                    version:
                                      type: string
                                      description: Version of the threat.
                                    variant:
                                      type: string
                                      description: Variant of the threat.
                            indicator_type:
                              type: string
                              description: "Describes the type of indicator: (e.g. file, ipv4, url)."
                            indicator_data:
                              type: object
                              description: Sub-document containing indicator type and value(s).
                              properties:
                                url:
                                  type: string
                                  description: The `url` of the indicator.
                                address:
                                  type: string
                                  description: Address
                                file:
                                  type: object
                                  description: File details
                                  properties:
                                    md5:
                                      type: string
                                      description: File's MD5 sum
                                    sha1:
                                      type: string
                                      description: File's SHA1 sum
                                    sha256:
                                      type: string
                                      description: File's SHA256 sum
                                    type:
                                      type: string
                                      description: File's type
                                    size:
                                      type: integer
                                      description: File's size
                                    ssdeep:
                                      type: string
                                      description: File's ssdeep hash (fuzzy hash)
                                    download_url:
                                      type: string
                                      description: File's download URL
                                geo_ip:
                                  type: object
                                  description: Geo IP
                                  properties:
                                    country:
                                      type: string
                                      description: Country
                                    country_code:
                                      type: string
                                      description: Country code
                                    city:
                                      type: string
                                      description: City
                                    subdivision:
                                      type: array
                                      description: Subdivision
                                      items:
                                        type: string
                                    isp:
                                      type: object
                                      description: ISP details
                                      properties:
                                        network:
                                          type: string
                                          description: Network
                                        autonomous_system:
                                          type: string
                                          description: Autonomous System
                                        isp:
                                          type: string
                                          description: ISP name
                                        organization:
                                          type: string
                                          description: Organization
                            expiration:
                              type: integer
                              description: Indicator should be removed from block lists at this date.
                            confidence:
                              type: string
                              description: "Indicators with `high` confidence are derived from a primary source and are verified. They can safely be used for blocking.
                              If indicators are from a primary source, but they have not been verified, then the confidence rating is reduced to `medium`. We recommend them for alerting or threat hunting.
                              An example of this is a controller URL extracted from a malware configuration file. The file is verified (high), but the controller URLs inside it’s configuration are not (medium).
                              Indicators that are derived from a third party source via pivoting are marked as `low` confidence unless they have been verified. We don’t publish many low confidence indicators."
                            context:
                              type: object
                              description: Sub-document containing contextual information to describe the observed malicious activity.
                              required:
                                - description
                              properties:
                                description:
                                  type: string
                                  description: Free form text describing the indicator context.
                            mitre_tactics:
                              type: string
                              description: The MITRE ATT&CK tactic classification.
                            intel_requirements:
                              type: array
                              description: List of General Intelligence Requirements matching this indicator.
                              items:
                                type: string
                        meta:
                          type: object
                          description: Meta data used to describe document version.
                          required:
                            - version
                          properties:
                            version:
                              type: string
                              description: Document `version`.
                        uid:
                          type: string
                          description: Unique indicator identifier.
                        activity:
                          type: object
                          description: Period an indicator was active.
                          required:
                            - first
                            - last
                          properties:
                            first:
                              type: integer
                              description: Start of the indicator activity range.
                            last:
                              type: integer
                              description: End of the indicator activity range.

