openapi: 3.0.3
info:
  title: Titan API v1
  version: 1.20.0
  description: Vulnerability (CVE) reports lookup API.
servers:
  - url: https://api.intel471.com/v1
    description: Production server.
paths:
  /cve/reports:
    get:
      summary: Search Vulnerability (CVE) Reports
      operationId: Search Vulnerability (CVE) Reports
      description: Get a list of Vulnerability (CVE) Reports matching filter criteria.
      parameters:
        - name: cveReport
          in: query
          description: Free text Vulnerability (CVE) Reports search.
          schema:
            type: string
          example: vulnerability
        - name: cveType
          in: query
          description: Search Vulnerability (CVE) Reports by type.
          schema:
            type: string
          examples:
            Buffer overflow:
              value: Buffer overflow
            Privilege escalation:
              value: Privilege escalation
            Memory corruption:
              value: Memory corruption
        - name: cveName
          in: query
          description: Search Vulnerability (CVE) reports by name.
          schema:
            type: string
          example: CVE-2015-6435
        - name: riskLevel
          in: query
          description: Search Vulnerability (CVE) Reports by risk level.
          schema:
            type: string
            enum:
              - high
              - medium
              - low
        - name: patchStatus
          in: query
          description: Search Vulnerability (CVE) Reports by patch status.
          schema:
            type: string
            enum:
              - available
              - some_available
              - unavailable
        - name: vendorName
          in: query
          description: Search Vulnerability (CVE) Reports by vendor name.
          schema:
            type: string
          example: Mozilla
        - name: productName
          in: query
          description: Search Vulnerability (CVE) Reports by product name.
          schema:
            type: string
          example: Microsoft
      responses:
        200:
          description: A JSON array of Vulnerability (CVE) reports.
          content:
            application/json:
              schema:
                type: object
                required:
                  - cveReportsTotalCount
                properties:
                  cveReportsTotalCount:
                    type: integer
                    description: Total count of matched Vulnerability (CVE) Reports.
                  postPartialResult:
                    type: boolean
                    description: Indicates whether response contains partial result. It could be in case when request took too long and was terminated by timeout.
                  cveReports:
                    type: array
                    description: List of `Vulnerability (CVE) Reports`.
                    items:
                      type: object
                      required:
                        - uid
                        - activity
                        - last_updated
                        - data
                      properties:
                        data:
                          type: object
                          description: Sub-document containing Vulnerability (CVE) Report data.
                          required:
                            - cve_report
                          properties:
                            cve_report:
                              type: object
                              description: Sub-document containing Vulnerability (CVE) Report information.
                              required:
                                - name
                                - cve_type
                                - risk_level
                                - cve_status
                                - poc
                              properties:
                                name:
                                  type: string
                                  description: Vulnerability (CVE) name.
                                cve_type:
                                  type: string
                                  description: "Type of Vulnerability (CVE), for example: `Buffer overflow`, `Privilege escalation`, `Memory corruption`."
                                risk_level:
                                  type: string
                                  description: "Intel 471 risk level of the Vulnerability (CVE). Allowed values: `high`, `medium`, `low`."
                                vendor_name:
                                  type: string
                                  description: Vendor name of the affected software.
                                product_name:
                                  type: string
                                  description: Product name of the affected software.
                                cve_status:
                                  type: string
                                  description: "`status_new` for recently added Vulnerability (CVE); `status_existing` for Vulnerability (CVE) being reported for a while; `status_historical` for phased out and not active at the moment. Allowed values: `status_existing`, `status_new`, `status_historical`."
                                interest_level:
                                  type: object
                                  description: Level of interest for the Vulnerability (CVE).
                                  properties:
                                    disclosed_publicly:
                                      type: boolean
                                      description: The Vulnerability (CVE) has been disclosed publicly.
                                    researched_publicly:
                                      type: boolean
                                      description: The Vulnerability (CVE) has been documented/researched publicly.
                                    exploit_sought:
                                      type: boolean
                                      description: A threat actor is seeking an exploit for the Vulnerability (CVE).
                                activity_location:
                                  type: object
                                  description: Location of activity/discussion for the Vulnerability (CVE).
                                  properties:
                                    location_opensource:
                                      type: boolean
                                      description: The Vulnerability (CVE) is being discussed in open source.
                                    location_underground:
                                      type: boolean
                                      description: The Vulnerability (CVE) is being discussed in the underground.
                                    location_private:
                                      type: boolean
                                      description: The Vulnerability (CVE) is being discussed in private/direct communications.
                                exploit_status:
                                  type: object
                                  description: The status of exploitation or exploit code for the Vulnerability (CVE).
                                  properties:
                                    available:
                                      type: boolean
                                      description: Exploit code is available for the Vulnerability (CVE).
                                    weaponized:
                                      type: boolean
                                      description: The Vulnerability (CVE) has been used in an attack or has been included in an exploit kit.
                                    productized:
                                      type: boolean
                                      description: There is a module for the Vulnerability (CVE) in commercial exploit kits or network security tools.
                                    not_observed:
                                      type: boolean
                                      description: Exploit code or usage has not been observed for the Vulnerability (CVE).
                                cvss_score:
                                  type: object
                                  description: Common Vulnerability Scoring System (CVSS) score reflecting the severity of the Vulnerability (CVE).
                                  properties:
                                    v2:
                                      type: number
                                      description: Common Vulnerability Scoring System (CVSS) score (version 2).
                                    v3:
                                      type: number
                                      description: Common Vulnerability Scoring System (CVSS) score (version 3).
                                patch_status:
                                  type: string
                                  description: "Indicates availability of a patch for the Vulnerability (CVE). Allowed values: `available`, `some_available`, `unavailable`."
                                underground_activity:
                                  type: string
                                  description: "Describes if underground activity has been observed for the Vulnerability (CVE). Allowed values: `observed`, `not_observed`."
                                underground_activity_summary:
                                  type: string
                                  description: Description of the underground activity for the Vulnerability (CVE).
                                cpe:
                                  type: object
                                  description: "CPE (Common Platform Enumeration) is the list of the software affected by the Vulnerability (CVE)."
                                summary:
                                  type: string
                                  description: Intel 471 summary of the Vulnerability (CVE).
                                detection:
                                  type: string
                                  description: "Detection (signatures, definitions) exists for the Vulnerability (CVE). Allowed values: `available`, `not_available`."
                                titan_links:
                                  type: array
                                  description: URL(s) of the related Intel 471 Titan items.
                                  items:
                                    type: object
                                    required:
                                      - title
                                      - url
                                    properties:
                                      title:
                                        type: string
                                        description: Title of the link URL.
                                      url:
                                        type: string
                                        description: Link URL.
                                poc:
                                  type: string
                                  description: "Proof of concept code or demonstration exists. Allowed values: `observed`, `not_observed`, `alleged_observed`."
                                poc_links:
                                  type: array
                                  description: URL(s) of Proofs of Concept for the Vulnerability (CVE).
                                  items:
                                    type: object
                                    required:
                                      - title
                                      - url
                                    properties:
                                      title:
                                        type: string
                                        description: Title of the Proof of Concept URL.
                                      url:
                                        type: string
                                        description: Proof of Concept URL.
                                counter_measures:
                                  type: string
                                  description: Summary of countermeasure(s) to protect against the Vulnerability (CVE).
                                counter_measure_links:
                                  type: array
                                  description: URL(s) of countermeasure information to protect against the Vulnerability (CVE).
                                  items:
                                    type: object
                                    required:
                                      - title
                                      - url
                                    properties:
                                      title:
                                        type: string
                                        description: Title of the countermeasure URL.
                                      url:
                                        type: string
                                        description: Countermeasure URL.
                                patch_links:
                                  type: array
                                  description: URL(s) to available vulnerability (CVE) patches.
                                  items:
                                    type: object
                                    required:
                                      - title
                                      - url
                                    properties:
                                      title:
                                        type: string
                                        description: Title of the patch URL.
                                      url:
                                        type: string
                                        description: Patch URL.
                        last_updated:
                          type: integer
                          format: int64
                          description: Last updated time of the Vulnerability (CVE) Report. Represented as milliseconds since the epoch. Please convert to human readable format.
                        uid:
                          type: string
                          description: Vulnerability (CVE) Report's unique identifier.
                        classification:
                          type: object
                          description: Classification of the Vulnerability (CVE) Report.
                          properties:
                            intel_requirements:
                              type: array
                              description: General Intel Requirements (GIRs).
                              items:
                                type: string
                        activity:
                          type: object
                          required:
                            - first
                            - last
                          description: Activity range for the Vulnerability (CVE) Report.
                          properties:
                            first:
                              type: integer
                              format: int64
                              description: Start time of the Vulnerability (CVE) Report activity range. Represented as milliseconds since the epoch. Please convert to human readable format.
                            last:
                              type: integer
                              format: int64
                              description: End time of the Vulnerability (CVE) Report activity range. Represented as milliseconds since the epoch. Please convert to human readable format.
        '401':
          description: Unauthorized
        '412':
          description: Precondition Failed
